### ISSUE TITLE
Connection

### ISSUE THREAD

**Issue by Original-Tasty** [TILTCoinIO/TILT#1]
Hello, any adnodes? ty

**Comment by TILTCoinIO** [comment]
Yes. Under TILT/contrib/seeds.

**Comment by le2Ks** [comment]
> 
> 
> Yes. Under TILT/contrib/seeds.

I've added those already but it won't connect.
Also the port in this file (main_seeds etc) for the nodes is set to 4444, while the correct p2p port is 44684

I've tried on both port, and without mentioning the ports but it won't connect to 
185.163.118.233 and 188.68.52.16  :(

I believe those nodes are for 'Parcoin'. The coin Tilt was forked from.

What peers do you see at the "peers" tab from your Qt wallet?
